import type { Metadata } from "next"
import "./globals.css"
import { Sidebar } from "@/components/sidebar/Sidebar"
import { sahelFont } from "@/public/fonts/font"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={sahelFont.className}>
        <Sidebar>{children}</Sidebar>
      </body>
    </html>
  )
}
